name: todolist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  path: any
  sqflite: ^2.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  roundcheckbox: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: akrobat_regular
      fonts:
        - asset: ./fonts/akrobat_regular.otf

    - family: akrobat_semibold
      fonts:
        - asset: ./fonts/akrobat_semibold.otf

    - family: google_regular
      fonts:
        - asset: ./fonts/google_regular.ttf

    - family: google_medium
      fonts:
        - asset: ./fonts/google_medium.ttf

    - family: google_bold
      fonts:
        - asset: ./fonts/google_bold.ttf

